#ifndef WORLDCOIN_CHAINPARAMSSEEDS_H
#define WORLDCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the worldcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {

};

static SeedSpec6 pnSeed6_test[] = {
/*    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x05,0x09,0x96,0x70}, 19335},
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0xd9,0x10,0xb9,0xaf}, 19335}*/
};
#endif // WORLDCOIN_CHAINPARAMSSEEDS_H
